### ISSUE TITLE
please show example of options

### ISSUE THREAD

**Issue by ORESoftware** [soldair/node-fs-backwards-stream#2]
using this 

```
 var fileStream = backwardsStream(stderr_path, {
        encoding: 'utf8'
    });
```

I get this error:

``` javascript
Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:533:11)
    at read (/Users/amills001c/WebstormProjects/smartconnect/node_modules/fs-backwards-stream/index.js:88:8)
    at fn (/Users/amills001c/WebstormProjects/smartconnect/node_modules/fs-backwards-stream/index.js:74:7)
    at Stream.s._readLoop (/Users/amills001c/WebstormProjects/smartconnect/node_modules/fs-backwards-stream/index.js:83:6)
    at /Users/amills001c/WebstormProjects/smartconnect/node_modules/fs-backwards-stream/index.js:49:20
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I think something is wrong with this lib because my file can be read without problems with fs.createReadStream

**Comment by soldair** [comment]
hmm. ill take a ;look

**Comment by soldair** [comment]
does it work with no encoding argument?

**Comment by ORESoftware** [comment]
thanks, I tried without encoding, same problem

btw

have you tried this?

``` javascript
process.exec('tail -n 5 ' + filepath).pipe(somewhere)
```

the above in theory will read the last 5 lines on a Mac or Unix box. but I can't get the tail command to work quite yet inside node, although it works from command line, but I think that's a better solution than riding on top of fs

will let you know if I solve that

**Comment by soldair** [comment]
process.exec calls back and doesn't stream stdout
https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

```
process.exec("tail -n 5",function(exit,stdout,stder){
// do stuff
})
```

**Comment by soldair** [comment]
its not a better solution than using fs. IMO child processes cost alot.
if you only need the last n lines im sure there is a module there for you

**Comment by ORESoftware** [comment]
ahh thanks will try that. I suppose you could streamify the results of that somehow, but if you only want 5-100 lines of a file, streams aren't as necessary (I guess)

**Comment by ORESoftware** [comment]
I don't think process.exec uses a child_process (?) I would assume (given the semantics) it uses the process at hand, but maybe not

there is this

var exec = require("child_process").exec;

**Comment by soldair** [comment]
yeah there is no "process.exec"

**Comment by ORESoftware** [comment]
yeah forgive me if I am wrong, but

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

require('child_process').exec() would mean the child_process does the execing

process.exec must be the same process

**Comment by soldair** [comment]
if you need the last n lines of a file use a module like `fs-reverse`
this is specifically if you need the get the contents backwards but no line parsing

**Comment by soldair** [comment]
if you get a moment to `cd node_modules/fs-backwards-stream && npm install && npm test` and let me know the result i would appreciate it

**Comment by soldair** [comment]
you can look at the tests for examples. im very curious how to reproduce your error.  https://github.com/soldair/node-fs-backwards-stream/blob/master/test/byteatatime.js

**Comment by ORESoftware** [comment]
yeah I will do that 

btw you're right, there is no process.exec

there is only

var cp = require('child_process');

cp.exec()

**Comment by soldair** [comment]
if you want to have a little fun and master streams and some more obscure parts of node you should really really try the nodeschool.io modules. they are amazing.

`sudo npm install -g learnyounode && learnyounode`
`sudo npm install -g stream-adventure && stream-adventure`

**Comment by ORESoftware** [comment]
cool man I will, I am weak on buffers & streams in all languages

**Comment by ORESoftware** [comment]
I ran an NPM update and I didn't see any changes to this module in my project, I can check again, what version to use/what's the latest?

**Comment by soldair** [comment]
this is the latest version of the module. i just wanted you to see if the
tests worked. if they do you can look at them and use them as an example to
solve your problem.

**Comment by soldair** [comment]
the tests do pass.

**Comment by ORESoftware** [comment]
ok I will let you know what I find out

**Comment by ORESoftware** [comment]
error in test

```
CACSVML-13295:node_modules amills001c$ cd fs-backwards-stream/
CACSVML-13295:fs-backwards-stream amills001c$ npm test

> fs-backwards-stream@0.0.0 test /Users/amills001c/WebstormProjects/smartconnect/node_modules/fs-backwards-stream
> tape test/*.js

sh: tape: command not found
npm ERR! Test failed.  See above for more details.
```

**Comment by ORESoftware** [comment]
i guess i need to do npm install -g tape...

**Comment by soldair** [comment]
no. you have to npm  install in the modules directory lie the command i sent you

**Comment by soldair** [comment]
cd fs-backwards-stream/ && npm install && npm test

**Comment by ORESoftware** [comment]
aye

**Comment by ORESoftware** [comment]
the tests pass

> fs-backwards-stream@0.0.0 test /Users/amills001c/WebstormProjects/smartconnect/node_modules/fs-backwards-stream
> tape test/*.js

TAP version 13

# can get a range 1 byte at a time

ok 1 should read only specified range

# can get a range 2 bytes at a time

ok 2 should read only specified range

# whole file

ok 3 should have read whole file

1..3

# tests 3

# pass  3

# ok

**Comment by ORESoftware** [comment]
does your lib work with both absolute paths and relative paths? because that's pretty much the only thing left that I can think of

**Comment by ORESoftware** [comment]
btw if you want to plug your lib you can plug it here

http://stackoverflow.com/questions/32234228/node-js-fs-stream-file-backwards-from-bottom-to-top

**Comment by soldair** [comment]
pposted a response if you want to upvote ;)
